CREATE OR REPLACE TRIGGER TRG_01
AFTER INSERT
ON EMPLOYEE
BEGIN
 DBMS_OUTPUT.PUT_LINE('신입사원이 입사했습니다.');
END;
/

INSERT INTO EMPLOYEE VALUES (905,'길성춘','690512-1151432','gil_sj@kh.or.kr','01035464455','D5','J3','S5',3000000,0.1,200,SYSDATE,NULL,DEFAULT);

SELECT * FROM EMPLOYEE;

CREATE TABLE PRODUCT(
 PCODE NUMBER PRIMARY KEY,
 PNAME VARCHAR2(30),
 BRAND VARCHAR2(30),
 PRICE NUMBER,
 STOCK NUMBER DEFAULT 0
);

SELECT * FROM PRODUCT;

CREATE TABLE PRO_DETAIL(
 DCODE NUMBER PRIMARY KEY,
 PCODE NUMBER,
 PDATE DATE,
 AMOUNT NUMBER,
 STATUS VARCHAR2(10) CHECK (STATUS IN('입고','출고')),
 FOREIGN KEY(PCODE) REFERENCES PRODUCT(PCODE)
);

SELECT * FROM PRO_DETAIL;

CREATE SEQUENCE SEQ_PCODE;
CREATE SEQUENCE SEQ_DCODE;

INSERT INTO PRODUCT
VALUES(SEQ_PCODE.NEXTVAL,'갤럭스노트8','삼셩',900000,DEFAULT);
INSERT INTO PRODUCT
VALUES(SEQ_PCODE.NEXTVAL,'아이포8','사과',1000000,DEFAULT);
INSERT INTO PRODUCT
VALUES(SEQ_PCODE.NEXTVAL,'중군폰','샤우미',60000,DEFAULT);

select * from tb_department;

DESC USER_CONSTRAINTS;